### ISSUE TITLE
AttributeError: module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by Te-k** [NullHypothesis/bibliograpy#4]
I have the following error when using it :

```
Traceback (most recent call last):
  File "../bibliograpy/bibliogra.py", line 549, in <module>
    sys.exit(main(args.OUTPUT_DIR, args.file_name, args.header, args.footer))
  File "../bibliograpy/bibliogra.py", line 510, in main
    header + sort_by_year(bibdata, output_dir) + footer)
  File "../bibliograpy/bibliogra.py", line 368, in sort_by_year
    html.append(format_html(bibkey, bibdata.entries[bibkey],
  File "../bibliograpy/bibliogra.py", line 263, in format_html
    (key, latex_to_html(bib_entry.fields["title"])))
  File "../bibliograpy/bibliogra.py", line 39, in latex_to_html
    return cgi.escape(string.decode("latex"), quote=True)
AttributeError: module 'cgi' has no attribute 'escape'
```

I feel it is an issue with python3 cgi changes, is bibliography python3 compatible? Or still python2?

**Comment by Te-k** [comment]
Yes it is indeed an issue with cgi not available in python3, `html.escape` should be used instead. Should I submit a PR for that? I am not sure how to have python 2 and 3 compatible code, but I guess we can drop python 2 now ?

**Comment by Te-k** [comment]
I fixed all python 3 related bugs here https://github.com/Te-k/ipvtechbib/blob/master/bibliogra.py (but it does not support python2)
